# Generated by Django 2.2 on 2019-11-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consommation',
            name='c_name',
        ),
        migrations.RemoveField(
            model_name='habitant',
            name='h_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='u_name',
        ),
        migrations.AddField(
            model_name='consommation',
            name='c_cons',
            field=models.CharField(default='somevalue', max_length=100),
        ),
        migrations.AddField(
            model_name='consommation',
            name='c_loc',
            field=models.CharField(default='somevalue', max_length=100),
        ),
        migrations.AddField(
            model_name='habitant',
            name='h_nom',
            field=models.CharField(default='somevalue', max_length=100),
        ),
        migrations.AddField(
            model_name='habitant',
            name='h_prenom',
            field=models.CharField(default='somevalue', max_length=100),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_adresse',
            field=models.CharField(default='somevalue', max_length=100),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_cp',
            field=models.CharField(default='somevalue', max_length=20),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_pays',
            field=models.CharField(default='somevalue', max_length=100),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_ville',
            field=models.CharField(default='somevalue', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='u_id',
            field=models.CharField(default='somevalue', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='u_mdp',
            field=models.CharField(default='123456', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='u_type',
            field=models.CharField(default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='logement',
            name='l_name',
            field=models.CharField(default='somevalue', max_length=100),
        ),
    ]
