# Generated by Django 2.2 on 2019-11-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20191120_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='u_type',
            field=models.CharField(default='U', max_length=1),
        ),
    ]
