# Generated by Django 2.2 on 2019-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20191120_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consommation',
            name='c_loc',
        ),
        migrations.AddField(
            model_name='consommation',
            name='c_loglink',
            field=models.ManyToManyField(to='home_page.Logement'),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_hablink',
            field=models.ManyToManyField(to='home_page.Habitant'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='u_hablink',
            field=models.ManyToManyField(to='home_page.Habitant'),
        ),
    ]
