# Generated by Django 2.2 on 2019-11-21 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20191121_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='c_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
