# Generated by Django 2.2 on 2019-11-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_consommation_c_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logement',
            name='l_adresse',
        ),
        migrations.RemoveField(
            model_name='logement',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='logement',
            name='l_pays',
        ),
        migrations.AddField(
            model_name='logement',
            name='l_annee',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_chauff',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_nb_pieces',
            field=models.CharField(default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_nb_voie',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_sur',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_type',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='logement',
            name='l_voie',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='logement',
            name='l_cp',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='logement',
            name='l_ville',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
