# Generated by Django 2.2 on 2019-11-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_auto_20191121_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='l_foyer',
            field=models.CharField(default='NA', max_length=2),
        ),
    ]
