# Generated by Django 2.2 on 2019-11-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_logement_l_foyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='l_ville',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
