# Generated by Django 2.2 on 2019-11-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_auto_20191121_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='l_nb_voie',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
