# Generated by Django 2.2 on 2019-11-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='p_nom',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='p_pre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='p_soc',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
