# Generated by Django 2.2 on 2019-11-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0012_auto_20191121_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='c_log',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='c_cons',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
