# Generated by Django 2.2 on 2019-11-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_auto_20191121_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consommation',
            name='c_date',
        ),
    ]
