# Generated by Django 2.2 on 2019-11-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0014_remove_consommation_c_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='c_date',
            field=models.CharField(blank=True, default='01/01/1901', max_length=10, null=True),
        ),
    ]
