# Generated by Django 2.2 on 2019-11-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0015_consommation_c_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='c_cons',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='c_date',
            field=models.CharField(blank=True, default='NA', max_length=10, null=True),
        ),
    ]
