# Generated by Django 2.2 on 2019-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0016_auto_20191121_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='c_log',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
