# Generated by Django 2.2 on 2019-11-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0017_auto_20191121_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='u_hablink',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='u_hablink',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='ref1', to='home_page.Habitant'),
        ),
    ]
