# Generated by Django 2.2 on 2019-11-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0018_auto_20191122_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='u_hablink',
            field=models.ForeignKey(default='9999', on_delete=django.db.models.deletion.CASCADE, related_name='ref1', to='home_page.Habitant'),
        ),
    ]
