# Generated by Django 2.2 on 2019-11-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0019_auto_20191122_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='u_hablink',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='u_hablink',
            field=models.ManyToManyField(to='home_page.Habitant'),
        ),
    ]
